import { CompanyProfile, Client, ProductItem, BillDocument, ChallanDocument } from '../types';
import { MATECH_LOGO_DATA_URL } from '../assets/logo';

export const DEFAULT_COMPANY: CompanyProfile = {
  name: 'M.A. TECH ENTERPRISE',
  tagline: 'CCTV Camera, Computer Accessories & Mobile Phone Accessories Specialist',
  bin: '003928174-0101', // 13-digit Bangladesh NBR Business Identification Number
  tin: '481928371902', // 12-digit e-TIN
  gstin: '003928174-0101',
  pan: '481928371902',
  email: 'matechenterprise.bd@gmail.com',
  phone: '01568799017',
  whatsapp: '01628491979',
  address: 'House 32, Block B, Section 11, Ave 7, Pallabi, Mirpur',
  city: 'Dhaka',
  state: 'Dhaka Division',
  pincode: '1216',
  country: 'Bangladesh',
  bankName: 'City Bank PLC / BRAC Bank PLC',
  bankAccountNo: '2103498172001',
  bankRoutingNo: '225261890',
  bankIfsc: '225261890',
  bankBranch: 'Mirpur-11 Branch, Dhaka',
  mfsNumber: '01628491979 / 01568799017 (bKash & Nagad Merchant / Personal)',
  upiId: '01628491979 (bKash)',
  currencySymbol: '৳',
  currencyCode: 'BDT',
  termsAndConditions: '১. সমস্ত সিসিটিভি ক্যামেরা ও কম্পিউটার যন্ত্রাংশের সাথে অফিসিয়াল ১/২ বছরের সার্ভিস বা রিপ্লেসমেন্ট ওয়ারেন্টি প্রযোজ্য।\n২. পণ্য ডেলিভারির সময় চালানপত্র (Delivery Challan) যাচাই করে গ্রহণ ও স্বাক্ষর করতে হবে।\n৩. পোড়া, ফিজিক্যাল ড্যামেজ ও ক্যাবলের ক্ষেত্রে কোনো ওয়ারেন্টি প্রযোজ্য হবে না।\n৪. বিল ইস্যুর তারিখ হতে ৭-১৫ কার্যদিবসের মধ্যে মূল্য পরিশোধযোগ্য (Cash/bKash/Nagad/Bank Transfer)।\n৫. যেকোনো সাপোর্ট ও তথ্যের জন্য WhatsApp: 01628491979 অথবা ফোন: 01568799017 এ যোগাযোগ করুন।',
  signatureTitle: 'Proprietor / Authorized Incharge',
  logoUrl: MATECH_LOGO_DATA_URL,
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_1',
    name: 'Engr. Kamrul Hasan',
    company: 'Mirpur Digital Diagnostic & Hospital Ltd.',
    email: 'admin@mirpurdigitalhospital.com',
    phone: '01712-458921',
    bin: '001928374-0101',
    tin: '381920194851',
    gstin: '001928374-0101',
    billingAddress: 'House 14, Main Road, Block C, Section 11, Pallabi',
    billingCity: 'Mirpur, Dhaka',
    billingState: 'Dhaka Division',
    billingPincode: '1216',
    shippingSameAsBilling: true,
    shippingAddress: 'House 14, Main Road, Block C, Section 11, Pallabi',
    shippingCity: 'Mirpur, Dhaka',
    shippingState: 'Dhaka Division',
    shippingPincode: '1216',
  },
  {
    id: 'cli_2',
    name: 'Zubair Ahmed',
    company: 'Al-Madina Shopping Complex Association',
    email: 'zubair.almadina@gmail.com',
    phone: '01819-332211',
    bin: '003819284-0204',
    tin: '592817264810',
    gstin: '003819284-0204',
    billingAddress: 'Level 4, Al-Madina Shopping Complex, Section 10 Roundabout',
    billingCity: 'Mirpur, Dhaka',
    billingState: 'Dhaka Division',
    billingPincode: '1216',
    shippingSameAsBilling: true,
    shippingAddress: 'Level 4, Al-Madina Shopping Complex, Section 10 Roundabout',
    shippingCity: 'Mirpur, Dhaka',
    shippingState: 'Dhaka Division',
    shippingPincode: '1216',
  },
  {
    id: 'cli_3',
    name: 'Nazmul Haque',
    company: 'Greenfield IT & Software Lab',
    email: 'procurement@greenfieldit-bd.com',
    phone: '01911-778899',
    bin: '000847291-0301',
    tin: '281948273619',
    gstin: '000847291-0301',
    billingAddress: 'Holding 88, Senpara Parbata, Main Road',
    billingCity: 'Mirpur-10, Dhaka',
    billingState: 'Dhaka Division',
    billingPincode: '1216',
    shippingSameAsBilling: true,
    shippingAddress: 'Holding 88, Senpara Parbata, Main Road',
    shippingCity: 'Mirpur-10, Dhaka',
    shippingState: 'Dhaka Division',
    shippingPincode: '1216',
  },
  {
    id: 'cli_4',
    name: 'Farzana Akhter',
    company: 'Prime Model High School & College',
    email: 'office@primemodel-school.edu.bd',
    phone: '01678-112233',
    bin: '001182734-0105',
    tin: '192837465019',
    gstin: '001182734-0105',
    billingAddress: 'Avenue 5, Block D, Section 11, Pallabi',
    billingCity: 'Mirpur, Dhaka',
    billingState: 'Dhaka Division',
    billingPincode: '1216',
    shippingSameAsBilling: true,
    shippingAddress: 'Avenue 5, Block D, Section 11, Pallabi',
    shippingCity: 'Mirpur, Dhaka',
    shippingState: 'Dhaka Division',
    shippingPincode: '1216',
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // CCTV Cameras & Security Equipment
  {
    id: 'prd_1',
    name: 'Hikvision 2MP HD 1080P Audio Bullet Camera',
    sku: 'HIK-DS-2CE16D0T-ITPFS',
    hsnCode: '852580',
    unit: 'Pcs',
    unitPrice: 1950,
    taxRate: 15,
    description: '20m Smart IR, Built-in Mic with Coaxial Audio, Weatherproof IP67, 2 Years Warranty',
    stock: 45,
  },
  {
    id: 'prd_2',
    name: 'Hikvision 8-Channel Turbo HD XVR / DVR (1080P Lite)',
    sku: 'HIK-DS-7208HGHI-K1',
    hsnCode: '852190',
    unit: 'Pcs',
    unitPrice: 5400,
    taxRate: 15,
    description: 'H.265+ Pro video compression, 1 SATA interface up to 10TB, HDMI & VGA output, 2 Years Warranty',
    stock: 16,
  },
  {
    id: 'prd_3',
    name: 'Western Digital Purple 2TB Surveillance Hard Drive',
    sku: 'WD-PUR-2TB-64MB',
    hsnCode: '847170',
    unit: 'Pcs',
    unitPrice: 6850,
    taxRate: 15,
    description: '24/7 AllFrame technology engineered for CCTV security video recording, 2 Years Replacement Warranty',
    stock: 22,
  },
  {
    id: 'prd_4',
    name: 'Dahua 4MP Full-Color Night Vision Dome Camera',
    sku: 'DH-HAC-HDW1400EMP-A',
    hsnCode: '852580',
    unit: 'Pcs',
    unitPrice: 2850,
    taxRate: 15,
    description: '24/7 Color Video with Warm LED 40m distance, Built-in Mic, 2 Years Official Warranty',
    stock: 30,
  },
  {
    id: 'prd_5',
    name: '12V 10A CCTV Central Metal Power Supply Box (9 Channel)',
    sku: 'PWR-12V10A-9CH',
    hsnCode: '850440',
    unit: 'Pcs',
    unitPrice: 1350,
    taxRate: 15,
    description: 'Regulated switching power adapter box with individual fuse protection for 8-16 CCTV cameras',
    stock: 35,
  },
  {
    id: 'prd_6',
    name: 'Hikvision Cat6 UTP Solid Copper Network Cable Box (305M)',
    sku: 'CBL-CAT6-305M-COP',
    hsnCode: '854449',
    unit: 'Box',
    unitPrice: 8900,
    taxRate: 15,
    description: 'Pure oxygen-free solid copper Cat6 4-pair 23AWG high speed gigabit transmission cable',
    stock: 14,
  },
  {
    id: 'prd_7',
    name: 'BNC Video Connector + DC Power Jack (Set of 8 Pairs)',
    sku: 'ACC-BNC-DC-SET8',
    hsnCode: '853669',
    unit: 'Set',
    unitPrice: 480,
    taxRate: 15,
    description: 'Heavy duty copper pin twist-on BNC connectors and solderless DC male plug adapter',
    stock: 60,
  },

  // Computer Accessories & Peripherals
  {
    id: 'prd_8',
    name: 'A4Tech KRS-85 USB Multimedia Keyboard & Optical Mouse Combo',
    sku: 'A4T-KRS-85-USB',
    hsnCode: '847160',
    unit: 'Set',
    unitPrice: 1050,
    taxRate: 15,
    description: 'Comfort round edge keycaps, laser engraved letters, 1000 DPI high precision optical sensor',
    stock: 50,
  },
  {
    id: 'prd_9',
    name: 'Logitech M170 Wireless Optical Mouse (2.4GHz USB)',
    sku: 'LOG-M170-WL',
    hsnCode: '847160',
    unit: 'Pcs',
    unitPrice: 880,
    taxRate: 15,
    description: '10-meter wireless range, 12-month battery life, plug and play nano receiver',
    stock: 40,
  },
  {
    id: 'prd_10',
    name: 'Transcend 256GB PCIe NVMe M.2 2280 High Speed SSD',
    sku: 'TRN-SSD-256GB-M2',
    hsnCode: '847170',
    unit: 'Pcs',
    unitPrice: 2650,
    taxRate: 15,
    description: '3D NAND flash, up to 2000 MB/s read speed, 3 Years Official Warranty',
    stock: 28,
  },
  {
    id: 'prd_11',
    name: 'HP 21.5" Full HD IPS Borderless LED Monitor (HP P22v G5)',
    sku: 'HP-MON-P22V-IPS',
    hsnCode: '852852',
    unit: 'Pcs',
    unitPrice: 11800,
    taxRate: 15,
    description: '1920x1080 FHD, 75Hz refresh rate, HDMI and VGA ports, 3 Years Warranty',
    stock: 12,
  },
  {
    id: 'prd_12',
    name: 'TP-Link Archer C6 AC1200 Dual-Band Gigabit Wi-Fi Router',
    sku: 'TPL-ARCH-C6-V4',
    hsnCode: '851762',
    unit: 'Pcs',
    unitPrice: 2850,
    taxRate: 15,
    description: '867 Mbps at 5 GHz + 300 Mbps at 2.4 GHz, 4 external antennas, MU-MIMO support, 1 Year Warranty',
    stock: 20,
  },

  // Phone Accessories & Mobile Gadgets
  {
    id: 'prd_13',
    name: 'Baseus 20W Super Si Quick Charger (Type-C PD Adapter)',
    sku: 'BAS-CHG-20W-PD',
    hsnCode: '850440',
    unit: 'Pcs',
    unitPrice: 950,
    taxRate: 15,
    description: 'Mini fast charger compatible with iPhone 11-16, Samsung & Android devices with overheat protection',
    stock: 55,
  },
  {
    id: 'prd_14',
    name: 'Remax 20000mAh Dual USB 22.5W Fast Power Bank (LED Display)',
    sku: 'RMX-PB-20000-22W',
    hsnCode: '850440',
    unit: 'Pcs',
    unitPrice: 1750,
    taxRate: 15,
    description: 'High capacity polymer battery, digital battery percentage screen, Type-C input/output',
    stock: 30,
  },
  {
    id: 'prd_15',
    name: 'Anker PowerLine+ II Type-C to Type-C 1.8M Braided Cable (60W)',
    sku: 'ANK-CBL-CC-18M',
    hsnCode: '854442',
    unit: 'Pcs',
    unitPrice: 850,
    taxRate: 15,
    description: 'Ultra-durable double-braided nylon fast charging and data sync cable, 18-month warranty',
    stock: 45,
  },
  {
    id: 'prd_16',
    name: 'Joyroom JR-T03S Pro ANC True Wireless Bluetooth Earbuds',
    sku: 'JYR-T03S-PRO-ANC',
    hsnCode: '851830',
    unit: 'Pcs',
    unitPrice: 2400,
    taxRate: 15,
    description: 'Active noise cancellation, transparency mode, wireless charging case, touch controls',
    stock: 25,
  },
];

export const INITIAL_BILLS: BillDocument[] = [
  {
    id: 'bill_1',
    type: 'bill',
    billNumber: 'INV-2026-0041',
    billDate: '2026-09-22',
    dueDate: '2026-10-15',
    poNumber: 'MDH-CCTV-2026',
    referenceChallanNo: 'CHL-2026-0018',
    clientId: 'cli_1',
    clientDetails: INITIAL_CLIENTS[0],
    items: [
      {
        id: 'bi_1',
        productId: 'prd_1',
        name: 'Hikvision 2MP HD 1080P Audio Bullet Camera',
        description: '20m Smart IR, Built-in Mic, Weatherproof IP67 (2 Years Warranty)',
        hsnCode: '852580',
        quantity: 8,
        unit: 'Pcs',
        unitPrice: 1950,
        discountPercent: 5,
        discountAmount: 780,
        taxRate: 15,
        taxableAmount: 14820,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 2223,
        total: 17043,
      },
      {
        id: 'bi_2',
        productId: 'prd_2',
        name: 'Hikvision 8-Channel Turbo HD XVR / DVR (1080P Lite)',
        description: 'H.265+ Pro compression, 1 SATA slot, HDMI & VGA output (2 Years Warranty)',
        hsnCode: '852190',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 5400,
        discountPercent: 5,
        discountAmount: 270,
        taxRate: 15,
        taxableAmount: 5130,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 769.5,
        total: 5899.5,
      },
      {
        id: 'bi_3',
        productId: 'prd_3',
        name: 'Western Digital Purple 2TB Surveillance Hard Drive',
        description: '24/7 Continuous Surveillance recording HDD (2 Years Warranty)',
        hsnCode: '847170',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 6850,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 6850,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 1027.5,
        total: 7877.5,
      },
      {
        id: 'bi_4',
        productId: 'prd_5',
        name: '12V 10A CCTV Central Metal Power Supply Box (9 Channel)',
        description: 'Regulated switching power unit with individual fuse channels',
        hsnCode: '850440',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 1350,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 1350,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 202.5,
        total: 1552.5,
      },
    ],
    subtotal: 29200,
    totalDiscount: 1050,
    totalTaxable: 28150,
    taxType: 'standard-vat',
    totalTax: 4222.5,
    cgstTotal: 0,
    sgstTotal: 0,
    igstTotal: 0,
    shippingCharges: 500,
    applyRoundOff: true,
    roundOff: -0.5,
    grandTotal: 32872,
    amountPaid: 32872,
    balanceDue: 0,
    paymentStatus: 'paid',
    paymentMethod: 'bKash Merchant Pay (TrxID: BK9281726354)',
    notes: 'Complete 8-Camera CCTV Surveillance Package installed at Hospital Reception & 2nd Floor Ward.',
    terms: DEFAULT_COMPANY.termsAndConditions,
    templateStyle: 'vat-mushak',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-25T14:30:00Z',
  },
  {
    id: 'bill_2',
    type: 'bill',
    billNumber: 'INV-2026-0042',
    billDate: '2026-09-29',
    dueDate: '2026-10-20',
    poNumber: 'AMC-PO-9912',
    referenceChallanNo: 'CHL-2026-0019',
    clientId: 'cli_2',
    clientDetails: INITIAL_CLIENTS[1],
    items: [
      {
        id: 'bi_5',
        productId: 'prd_8',
        name: 'A4Tech KRS-85 USB Multimedia Keyboard & Optical Mouse Combo',
        description: 'Laser carved keys, spill resistant, USB high speed',
        hsnCode: '847160',
        quantity: 6,
        unit: 'Set',
        unitPrice: 1050,
        discountPercent: 4,
        discountAmount: 252,
        taxRate: 15,
        taxableAmount: 6048,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 907.2,
        total: 6955.2,
      },
      {
        id: 'bi_6',
        productId: 'prd_11',
        name: 'HP 21.5" Full HD IPS Borderless LED Monitor (HP P22v G5)',
        description: 'FHD 1080p, HDMI/VGA, 3 Years Warranty',
        hsnCode: '852852',
        quantity: 2,
        unit: 'Pcs',
        unitPrice: 11800,
        discountPercent: 3,
        discountAmount: 708,
        taxRate: 15,
        taxableAmount: 22892,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 3433.8,
        total: 26325.8,
      },
      {
        id: 'bi_7',
        productId: 'prd_13',
        name: 'Baseus 20W Super Si Quick Charger (Type-C PD Adapter)',
        description: 'Type-C PD fast wall charger for mobile accessories',
        hsnCode: '850440',
        quantity: 5,
        unit: 'Pcs',
        unitPrice: 950,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 4750,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 712.5,
        total: 5462.5,
      },
    ],
    subtotal: 34650,
    totalDiscount: 960,
    totalTaxable: 33690,
    taxType: 'standard-vat',
    totalTax: 5053.5,
    cgstTotal: 0,
    sgstTotal: 0,
    igstTotal: 0,
    shippingCharges: 250,
    applyRoundOff: true,
    roundOff: 0.5,
    grandTotal: 38994,
    amountPaid: 20000,
    balanceDue: 18994,
    paymentStatus: 'partial',
    paymentMethod: 'Cash Advance ৳20,000 (Balance Due: ৳18,994)',
    notes: 'Delivered to Al-Madina Shopping Complex Office. Balance payable within 15 days.',
    terms: DEFAULT_COMPANY.termsAndConditions,
    templateStyle: 'classic',
    createdAt: '2026-09-29T11:20:00Z',
    updatedAt: '2026-09-29T11:20:00Z',
  },
];

export const INITIAL_CHALLANS: ChallanDocument[] = [
  {
    id: 'chl_1',
    type: 'challan',
    challanNumber: 'CHL-2026-0018',
    challanDate: '2026-09-22',
    challanType: 'mushak-6.5',
    dispatchMode: 'road',
    vehicleNumber: 'Dhaka Metro-Ta 14-8891 (Delivery Van)',
    transporterName: 'M.A. Tech In-House Logistics & Installation Team',
    lrNumber: 'LR-2026-MIR-098',
    ewayBillNo: '',
    driverName: 'Md. Rony Mia',
    driverContact: '01715-992288',
    clientId: 'cli_1',
    clientDetails: INITIAL_CLIENTS[0],
    items: [
      {
        id: 'ci_1',
        productId: 'prd_1',
        name: 'Hikvision 2MP HD 1080P Audio Bullet Camera',
        description: 'S/N: HK20260901 ~ HK20260908 (8 Units with Mounting Brackets)',
        hsnCode: '852580',
        quantity: 8,
        unit: 'Pcs',
        unitPrice: 1950,
        discountPercent: 5,
        discountAmount: 780,
        taxRate: 15,
        taxableAmount: 14820,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 2223,
        total: 17043,
      },
      {
        id: 'ci_2',
        productId: 'prd_2',
        name: 'Hikvision 8-Channel Turbo HD XVR / DVR (1080P Lite)',
        description: 'S/N: DVR-7208-BD-99182 with Power Adapter & USB Mouse',
        hsnCode: '852190',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 5400,
        discountPercent: 5,
        discountAmount: 270,
        taxRate: 15,
        taxableAmount: 5130,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 769.5,
        total: 5899.5,
      },
      {
        id: 'ci_3',
        productId: 'prd_3',
        name: 'Western Digital Purple 2TB Surveillance Hard Drive',
        description: 'S/N: WDC-PUR2TB-889102 (Installed inside DVR)',
        hsnCode: '847170',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 6850,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 6850,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 1027.5,
        total: 7877.5,
      },
      {
        id: 'ci_4',
        productId: 'prd_5',
        name: '12V 10A CCTV Central Metal Power Supply Box (9 Channel)',
        description: 'Key & Lock Metal Casing Box with Fuse Spares',
        hsnCode: '850440',
        quantity: 1,
        unit: 'Pcs',
        unitPrice: 1350,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 1350,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 202.5,
        total: 1552.5,
      },
    ],
    status: 'delivered',
    convertedToBillId: 'bill_1',
    totalQuantity: 11,
    totalEstimatedValue: 32872,
    templateStyle: 'standard',
    notes: 'পণ্যসমূহ অক্ষত অবস্থায় বুঝে নেওয়া হয়েছে। সিসিটিভি ক্যামেরা স্থাপন ও কেবলিং সম্পন্ন।',
    terms: '১. চালানপত্রের পণ্য সামগ্রী শারীরিক পরীক্ষা পূর্বক বুঝে নিতে হবে।\n২. রিসিভারের সই ও সিল ব্যতীত কোনো দাবি গ্রহণযোগ্য হবে না।\n৩. ওয়ারেন্টি সংক্রান্ত বিষয়ে মূল চালান কপি সংরক্ষণ করুন।',
    createdAt: '2026-09-22T09:00:00Z',
    updatedAt: '2026-09-22T12:00:00Z',
  },
  {
    id: 'chl_2',
    type: 'challan',
    challanNumber: 'CHL-2026-0019',
    challanDate: '2026-09-29',
    challanType: 'delivery',
    dispatchMode: 'hand',
    vehicleNumber: 'Hand Delivery by Courier / Staff',
    transporterName: 'M.A. Tech Store Executive',
    lrNumber: 'DIR-2026-MIR-044',
    ewayBillNo: '',
    driverName: 'Md. Shakil Hossain',
    driverContact: '01568799017',
    clientId: 'cli_2',
    clientDetails: INITIAL_CLIENTS[1],
    items: [
      {
        id: 'ci_5',
        productId: 'prd_8',
        name: 'A4Tech KRS-85 USB Multimedia Keyboard & Optical Mouse Combo',
        description: '6 Sets in Original Retail Packaging',
        hsnCode: '847160',
        quantity: 6,
        unit: 'Set',
        unitPrice: 1050,
        discountPercent: 4,
        discountAmount: 252,
        taxRate: 15,
        taxableAmount: 6048,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 907.2,
        total: 6955.2,
      },
      {
        id: 'ci_6',
        productId: 'prd_11',
        name: 'HP 21.5" Full HD IPS Borderless LED Monitor (HP P22v G5)',
        description: 'S/N: HP-MON-66291, HP-MON-66292 (Sealed Box with HDMI Cable)',
        hsnCode: '852852',
        quantity: 2,
        unit: 'Pcs',
        unitPrice: 11800,
        discountPercent: 3,
        discountAmount: 708,
        taxRate: 15,
        taxableAmount: 22892,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 3433.8,
        total: 26325.8,
      },
      {
        id: 'ci_7',
        productId: 'prd_13',
        name: 'Baseus 20W Super Si Quick Charger (Type-C PD Adapter)',
        description: 'Original Hologram Verified Boxes',
        hsnCode: '850440',
        quantity: 5,
        unit: 'Pcs',
        unitPrice: 950,
        discountPercent: 0,
        discountAmount: 0,
        taxRate: 15,
        taxableAmount: 4750,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 0,
        taxAmount: 712.5,
        total: 5462.5,
      },
    ],
    status: 'delivered',
    convertedToBillId: 'bill_2',
    totalQuantity: 13,
    totalEstimatedValue: 38743.5,
    templateStyle: 'standard',
    notes: 'Al-Madina Shopping Complex অফিস রিসিপশনে ডেলিভারি প্রদান সম্পন্ন হয়েছে।',
    terms: '১. পণ্য বুঝিয়া পাইয়া স্বাক্ষর করিলাম।\n২. ওয়ারেন্টি সংক্রান্ত দাবির জন্য চালানপত্রটি সংরক্ষণ করুন।',
    createdAt: '2026-09-29T10:30:00Z',
    updatedAt: '2026-09-29T11:15:00Z',
  },
];
